### ISSUE TITLE
reorient_intervals problem at import

### ISSUE THREAD

**Issue by ehildebr** [hunt-genes/ncls#7]
I'm having trouble importing version `ncls==0.0.30`, either installed by `pip install ncls` or `pip install git+https://github.com/hunt-genes/ncls.git` within a conda environment. 

I'm getting an import error: 
```
Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 02:32:25)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ncls
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/USER/bin/miniconda3/envs/bootcamp3-env/lib/python3.6/site-packages/ncls/__init__.py", line 2, in <module>
    from ncls.src.ncls32 import NCLS32
ImportError: /home/USER/bin/miniconda3/envs/bootcamp3-env/lib/python3.6/site-packages/ncls/src/ncls32.cpython-36m-x86_64-linux-gnu.so: undefined symbol: reorient_intervals
```

Looks like there is a problem with reorient_intervals?

Any advice on how to fix this?

Thanks!

**Comment by ehildebr** [comment]
It seems to work if I go back a few commits to the Sep 17th one (before reorient_intervals changes), so maybe something about the more recent commits is causing the problem? 

Thanks!

**Comment by endrebak** [comment]
Thanks for reporting. I might have forgotten that symbol in my new 32-bit version. Does `pip install ncls==0.0.31` work?

**Comment by ehildebr** [comment]
Yes - ncls 0.0.31 works! No problem with reorient_ranges upon import with that version. 

Thank you!

**Comment by endrebak** [comment]
Thanks for reporting once more. I am amazed that people have heard about ncls and are able to use it as I have made no effort to make it user-friendly. I will do so soon though :)

**Comment by ehildebr** [comment]
Thanks for developing ncls! I came to it from pyranges, since I've recently switched from R to Python, and was looking for something with GRanges like functionality - pyranges came up as an option, and I have found it really useful so far - looking forward to seeing what you add to that in the future as well!
